name: etl_dbt_project
version: 1.0.0
config-version: 2

profile: etl_dbt_project

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  etl_dbt_project:
    +schema: public
    +materialized: table
