FROM apache/airflow:2.7.1-python3.11

USER root
RUN apt-get update && apt-get install -y gcc build-essential libpq-dev
USER airflow

COPY --chown=airflow:airflow airflow_requirements.txt /opt/airflow/airflow_requirements.txt
RUN pip install --no-cache-dir -r /opt/airflow/airflow_requirements.txt

WORKDIR /opt/airflow
